// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechOps.Api.Data;

#nullable disable

namespace TechOps.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811080419_AddJwtAuthSeedPasswordHashes")]
    partial class AddJwtAuthSeedPasswordHashes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechOps.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("CommissionedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TechnicalSystemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicalSystemId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Brand = "DemoPower",
                            Code = "EQ-00032",
                            CommissionedAt = new DateOnly(2018, 3, 15),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Model = "G-750X",
                            Name = "Generator-T2-01",
                            SerialNo = "SN-DEMO-00032",
                            Status = "Active",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Brand = "DemoUPS",
                            Code = "EQ-00045",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Model = "UPS-200",
                            Name = "UPS-EM-02",
                            SerialNo = "SN-DEMO-00045",
                            Status = "Active",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Brand = "DemoAir",
                            Code = "EQ-00051",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Model = "AHU-400",
                            Name = "AHU-T1-04",
                            SerialNo = "SN-DEMO-00051",
                            Status = "Maintenance",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Brand = "DemoPLC",
                            Code = "EQ-00067",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Model = "PLC-1500",
                            Name = "PLC-PNL-03",
                            SerialNo = "SN-DEMO-00067",
                            Status = "Active",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.Fault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaultNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResolutionDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TechnicalSystemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaitingReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FaultNo")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("Priority");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicalSystemId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("Faults");
                });

            modelBuilder.Entity("TechOps.Api.Entities.FaultAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FaultId");

                    b.HasIndex("UserId");

                    b.ToTable("FaultActions");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "LOC-T1",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Terminal 1",
                            Type = "Terminal"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "LOC-T2",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Terminal 2",
                            Type = "Terminal"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "LOC-EM",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Enerji Merkezi",
                            Type = "Teknik Alan"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "LOC-TB",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Teknik Blok",
                            Type = "Teknik Alan"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "LOC-APR",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Apron Bölgesi",
                            Type = "Saha"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PlanNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ResponsibleUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PlanNo")
                        .IsUnique();

                    b.HasIndex("PlannedDate");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("Status");

                    b.ToTable("MaintenancePlans");
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MaintenancePlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedMaterials")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MaintenancePlanId");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sistem yöneticisi",
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Operasyonu ve raporları izler",
                            IsSystemRole = true,
                            Name = "Yönetici"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arıza, bakım ve test işlemlerini yürütür",
                            IsSystemRole = true,
                            Name = "Teknik Personel"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Olay ve arıza kaydı oluşturur",
                            IsSystemRole = true,
                            Name = "Operatör"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dashboard ve raporları görüntüler",
                            IsSystemRole = true,
                            Name = "Rapor Kullanıcısı"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftHandover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriticalNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("HandoverFromUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("HandoverNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("HandoverToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HandoverFromUserId");

                    b.HasIndex("HandoverNo")
                        .IsUnique();

                    b.HasIndex("HandoverToUserId");

                    b.HasIndex("ShiftDate");

                    b.HasIndex("ShiftType");

                    b.ToTable("ShiftHandovers");
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FaultId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("MaintenancePlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ShiftHandoverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FaultId");

                    b.HasIndex("MaintenancePlanId");

                    b.HasIndex("ShiftHandoverId");

                    b.ToTable("ShiftItems");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TechnicalSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TechnicalSystems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "SYS-GEN",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Jeneratör"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "SYS-UPS",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "UPS"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "SYS-HVAC",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "HVAC"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Code = "SYS-ELC",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Elektrik"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Code = "SYS-AUT",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Otomasyon Paneli"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ResponsibleUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PlannedDate");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("Status");

                    b.ToTable("TestPlans");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbnormalCondition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TestPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Result");

                    b.HasIndex("TestDate");

                    b.HasIndex("TestPlanId");

                    b.HasIndex("TestedByUserId");

                    b.ToTable("TestRecords");
                });

            modelBuilder.Entity("TechOps.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BT",
                            Email = "admin@demo.local",
                            FullName = "Admin Kullanıcı",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy1hZG1pbi0wMQ==$4bPH94C+/0I4E/NcauyxiZTaIRbc+p919s+gnQiXw4I=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Title = "Sistem Yöneticisi",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Teknik Otomasyon",
                            Email = "yonetici@demo.local",
                            FullName = "Teknik Yönetici",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy1tYW5hZ2VyMQ==$2JU5bt9x2uS/3kp8oY1vE/qobOLfoTy1SkB90ybtopU=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Title = "Teknik Yönetici",
                            Username = "yonetici"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Teknik Otomasyon",
                            Email = "teknik1@demo.local",
                            FullName = "Teknik Personel 1",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy10ZWNoLTAwMQ==$sf498N38LrE5MyaWcpBXOto0kRMQNFh+bvhz0I6fpSQ=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Title = "Teknik Personel",
                            Username = "teknik1"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operasyon",
                            Email = "operator1@demo.local",
                            FullName = "Operatör 1",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy1vcGVyLTAwMQ==$f3lnNMIH5Qx0gyXdU4xxnWGdeU3DhcO+MKX/Xooisp0=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Title = "Operatör",
                            Username = "operator1"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Equipment", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Location", "Location")
                        .WithMany("Equipment")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.TechnicalSystem", "TechnicalSystem")
                        .WithMany("Equipment")
                        .HasForeignKey("TechnicalSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("TechnicalSystem");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Fault", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "AssignedToUser")
                        .WithMany("AssignedFaults")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.User", "ClosedByUser")
                        .WithMany("ClosedFaults")
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.User", "CreatedByUser")
                        .WithMany("CreatedFaults")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("Faults")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.Location", "Location")
                        .WithMany("Faults")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "ResolvedByUser")
                        .WithMany("ResolvedFaults")
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.TechnicalSystem", "TechnicalSystem")
                        .WithMany("Faults")
                        .HasForeignKey("TechnicalSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("ClosedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Equipment");

                    b.Navigation("Location");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("TechnicalSystem");
                });

            modelBuilder.Entity("TechOps.Api.Entities.FaultAction", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Fault", "Fault")
                        .WithMany("Actions")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "User")
                        .WithMany("FaultActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fault");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Location", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Location", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenancePlan", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "CreatedByUser")
                        .WithMany("CreatedMaintenancePlans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("MaintenancePlans")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "ResponsibleUser")
                        .WithMany("ResponsibleMaintenancePlans")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Equipment");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany("Records")
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechOps.Api.Entities.User", "PerformedByUser")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("MaintenancePlan");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Notification", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftHandover", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "HandoverFromUser")
                        .WithMany("ShiftHandoversFrom")
                        .HasForeignKey("HandoverFromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "HandoverToUser")
                        .WithMany("ShiftHandoversTo")
                        .HasForeignKey("HandoverToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandoverFromUser");

                    b.Navigation("HandoverToUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftItem", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("ShiftItems")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.Fault", "Fault")
                        .WithMany("ShiftItems")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany("ShiftItems")
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.ShiftHandover", "ShiftHandover")
                        .WithMany("Items")
                        .HasForeignKey("ShiftHandoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Fault");

                    b.Navigation("MaintenancePlan");

                    b.Navigation("ShiftHandover");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestPlan", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("TestPlans")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "ResponsibleUser")
                        .WithMany("ResponsibleTestPlans")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestRecord", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("TestRecords")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.TestPlan", "TestPlan")
                        .WithMany("Records")
                        .HasForeignKey("TestPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechOps.Api.Entities.User", "TestedByUser")
                        .WithMany("TestRecords")
                        .HasForeignKey("TestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("TestPlan");

                    b.Navigation("TestedByUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.User", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Equipment", b =>
                {
                    b.Navigation("Faults");

                    b.Navigation("MaintenancePlans");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("ShiftItems");

                    b.Navigation("TestPlans");

                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Fault", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("ShiftItems");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Location", b =>
                {
                    b.Navigation("ChildLocations");

                    b.Navigation("Equipment");

                    b.Navigation("Faults");
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenancePlan", b =>
                {
                    b.Navigation("Records");

                    b.Navigation("ShiftItems");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftHandover", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TechnicalSystem", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Faults");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestPlan", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("TechOps.Api.Entities.User", b =>
                {
                    b.Navigation("AssignedFaults");

                    b.Navigation("AuditLogs");

                    b.Navigation("ClosedFaults");

                    b.Navigation("CreatedFaults");

                    b.Navigation("CreatedMaintenancePlans");

                    b.Navigation("FaultActions");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Notifications");

                    b.Navigation("ResolvedFaults");

                    b.Navigation("ResponsibleMaintenancePlans");

                    b.Navigation("ResponsibleTestPlans");

                    b.Navigation("ShiftHandoversFrom");

                    b.Navigation("ShiftHandoversTo");

                    b.Navigation("TestRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
