// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechOps.Api.Data;

#nullable disable

namespace TechOps.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812083712_RenameLocationsToLevelAndTerminalLetters")]
    partial class RenameLocationsToLevelAndTerminalLetters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechOps.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("CommissionedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TechnicalSystemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicalSystemId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Brand = "DemoPower",
                            Code = "EQ-00032",
                            CommissionedAt = new DateOnly(2018, 3, 15),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Model = "G-750X",
                            Name = "Generator-T2-01",
                            SerialNo = "SN-DEMO-00032",
                            Status = "Active",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Brand = "DemoUPS",
                            Code = "EQ-00045",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Model = "UPS-200",
                            Name = "UPS-LM-02",
                            SerialNo = "SN-DEMO-00045",
                            Status = "Active",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Brand = "DemoAir",
                            Code = "EQ-00051",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Model = "AHU-400",
                            Name = "AHU-T1-04",
                            SerialNo = "SN-DEMO-00051",
                            Status = "Maintenance",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Brand = "DemoPLC",
                            Code = "EQ-00067",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Model = "PLC-1500",
                            Name = "PLC-PNL-03",
                            SerialNo = "SN-DEMO-00067",
                            Status = "Active",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.Fault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaultNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResolutionDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TechnicalSystemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaitingReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FaultNo")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("Priority");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicalSystemId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("Faults");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000010"),
                            AssignedAt = new DateTime(2026, 8, 12, 7, 30, 0, 0, DateTimeKind.Utc),
                            AssignedToUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 12, 7, 10, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "UPS bypass hattında kısa süreli alarm gözlendi. Yük transferi ve alarm eşiği takip edilecek.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000002"),
                            FaultNo = "ARZ-2026-010",
                            LocationId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Priority = "Critical",
                            Source = "ScadaObservation",
                            Status = "InProgress",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 8, 12, 7, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000011"),
                            AssignedAt = new DateTime(2026, 8, 12, 9, 15, 0, 0, DateTimeKind.Utc),
                            AssignedToUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000004"),
                            Description = "AHU-T1-04 besleme havası sıcaklığı hedef aralığa düşmüyor. Filtre ve sensör kontrolleri takip edilecek.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000003"),
                            FaultNo = "ARZ-2026-011",
                            LocationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Priority = "High",
                            Source = "FieldObservation",
                            Status = "Assigned",
                            TechnicalSystemId = new Guid("30000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 8, 12, 9, 15, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.FaultAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FaultId");

                    b.HasIndex("UserId");

                    b.ToTable("FaultActions");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "LOC-T1",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Terminal A",
                            Type = "Terminal"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "LOC-T2",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Terminal B",
                            Type = "Terminal"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "LOC-EM",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Level Merkez",
                            Type = "Teknik Alan"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "LOC-TB",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Teknik Blok",
                            Type = "Teknik Alan"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "LOC-APR",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Apron Bölgesi",
                            Type = "Saha"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PlanNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ResponsibleUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PlanNo")
                        .IsUnique();

                    b.HasIndex("PlannedDate");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("MaintenancePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "Jeneratör yakıt, yağ, filtre ve otomatik transfer panosu kontrolleri yapılacak.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Frequency = "6 Aylık",
                            MaintenanceType = "6 Aylık",
                            PlanNo = "BKM-2026-001",
                            PlannedDate = new DateOnly(2026, 8, 20),
                            Priority = "Medium",
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Status = "Planned"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "HVAC ünitesi filtre, kayış, drenaj hattı ve sıcaklık sensörü kontrolleri yapılacak.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Frequency = "Aylık",
                            MaintenanceType = "Aylık",
                            PlanNo = "BKM-2026-002",
                            PlannedDate = new DateOnly(2026, 8, 11),
                            Priority = "High",
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            StartedAt = new DateTime(2026, 8, 11, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Started",
                            UpdatedAt = new DateTime(2026, 8, 11, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "UPS batarya bloğu, bypass hattı ve yük aktarım testi planlandı.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Frequency = "Yıllık",
                            MaintenanceType = "Yıllık",
                            PlanNo = "BKM-2026-003",
                            PlannedDate = new DateOnly(2026, 8, 5),
                            Priority = "Critical",
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Status = "Planned"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            CompletedAt = new DateTime(2026, 8, 1, 11, 20, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "PLC panel klemens, güç kaynağı ve haberleşme modülü bakımı tamamlandı.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000004"),
                            Frequency = "3 Aylık",
                            MaintenanceType = "3 Aylık",
                            PlanNo = "BKM-2026-004",
                            PlannedDate = new DateOnly(2026, 8, 1),
                            Priority = "Medium",
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            StartedAt = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            UpdatedAt = new DateTime(2026, 8, 1, 11, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            CompletedAt = new DateTime(2026, 7, 28, 8, 25, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "Haftalık jeneratör saha kontrolü tamamlandı.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Frequency = "Haftalık",
                            MaintenanceType = "Haftalık",
                            PlanNo = "BKM-2026-005",
                            PlannedDate = new DateOnly(2026, 7, 28),
                            Priority = "Low",
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            StartedAt = new DateTime(2026, 7, 28, 7, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            UpdatedAt = new DateTime(2026, 7, 28, 8, 25, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MaintenancePlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedMaterials")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MaintenancePlanId");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("MaintenanceRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000001"),
                            ChecklistJson = "[{\"Text\":\"Fiziksel hasar kontrolü yapıldı.\",\"IsChecked\":true},{\"Text\":\"Bağlantı klemensleri sıkıldı.\",\"IsChecked\":true},{\"Text\":\"Haberleşme testi yapıldı.\",\"IsChecked\":true}]",
                            CompletedAt = new DateTime(2026, 8, 1, 11, 20, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 8, 1, 11, 20, 0, 0, DateTimeKind.Utc),
                            Description = "PLC panel içi temizlik, klemens sıkılık kontrolü ve yedek güç kaynağı testi tamamlandı.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000004"),
                            MaintenancePlanId = new Guid("70000000-0000-0000-0000-000000000004"),
                            MaintenanceType = "3 Aylık",
                            PerformedByUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ResultStatus = "Completed",
                            StartedAt = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            UsedMaterials = "Klemens etiketi, temizlik spreyi"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000002"),
                            ChecklistJson = "[{\"Text\":\"Yağ ve yakıt seviyesi kontrol edildi.\",\"IsChecked\":true},{\"Text\":\"Sızıntı kontrolü yapıldı.\",\"IsChecked\":true},{\"Text\":\"Test çalıştırması tamamlandı.\",\"IsChecked\":true}]",
                            CompletedAt = new DateTime(2026, 7, 28, 8, 25, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 7, 28, 8, 25, 0, 0, DateTimeKind.Utc),
                            Description = "Jeneratör çalışma testi, sıvı seviye kontrolleri ve görsel saha kontrolü tamamlandı.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            MaintenancePlanId = new Guid("70000000-0000-0000-0000-000000000005"),
                            MaintenanceType = "Haftalık",
                            PerformedByUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ResultStatus = "Completed",
                            StartedAt = new DateTime(2026, 7, 28, 7, 45, 0, 0, DateTimeKind.Utc),
                            UsedMaterials = "Kontrol formu"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sistem yöneticisi",
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Operasyonu ve raporları izler",
                            IsSystemRole = true,
                            Name = "Yönetici"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arıza, bakım ve test işlemlerini yürütür",
                            IsSystemRole = true,
                            Name = "Teknik Personel"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Olay ve arıza kaydı oluşturur",
                            IsSystemRole = true,
                            Name = "Operatör"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dashboard ve raporları görüntüler",
                            IsSystemRole = true,
                            Name = "Rapor Kullanıcısı"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftHandover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriticalNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("HandoverFromUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("HandoverNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("HandoverToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HandoverFromUserId");

                    b.HasIndex("HandoverNo")
                        .IsUnique();

                    b.HasIndex("HandoverToUserId");

                    b.HasIndex("ShiftDate");

                    b.HasIndex("ShiftType");

                    b.ToTable("ShiftHandovers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            CriticalNotes = "Level Merkez UPS alarm eşiği ve yük transfer davranışı yakından izlenecek.",
                            HandoverFromUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            HandoverNo = "VDT-2026-001",
                            HandoverToUserId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ShiftDate = new DateOnly(2026, 8, 12),
                            ShiftType = "Morning",
                            Summary = "Gece vardiyasından devralınan UPS alarmı ve bekleyen bakım faaliyetleri sabah vardiyasına aktarıldı."
                        },
                        new
                        {
                            Id = new Guid("74000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            CriticalNotes = "Terminal A HVAC sıcaklık takibi operasyon saatleri boyunca sürdürülecek.",
                            HandoverFromUserId = new Guid("40000000-0000-0000-0000-000000000002"),
                            HandoverNo = "VDT-2026-002",
                            HandoverToUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ShiftDate = new DateOnly(2026, 8, 12),
                            ShiftType = "Evening",
                            Summary = "Sabah vardiyasındaki açık arıza ve saha takip maddeleri akşam vardiyasına devredildi."
                        },
                        new
                        {
                            Id = new Guid("74000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 12, 23, 45, 0, 0, DateTimeKind.Utc),
                            CriticalNotes = "Level Merkez çalışma izni ve PLC panel alarm listesi gece vardiyasında tekrar kontrol edilecek.",
                            HandoverFromUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            HandoverNo = "VDT-2026-003",
                            HandoverToUserId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ShiftDate = new DateOnly(2026, 8, 12),
                            ShiftType = "Night",
                            Summary = "Akşam vardiyasından gece vardiyasına takip edilecek cihazlar ve kritik saha notları aktarıldı."
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FaultId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("MaintenancePlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ShiftHandoverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FaultId");

                    b.HasIndex("MaintenancePlanId");

                    b.HasIndex("ShiftHandoverId");

                    b.ToTable("ShiftItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UPS bypass alarmının tekrarlayıp tekrarlamadığı SCADA üzerinden izlenecek.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000002"),
                            FaultId = new Guid("60000000-0000-0000-0000-000000000010"),
                            IsCompleted = false,
                            ItemType = "OpenFault",
                            Priority = "Critical",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000001"),
                            Title = "ARZ-2026-010 - UPS bypass alarmı takibi"
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 12, 8, 2, 0, 0, DateTimeKind.Utc),
                            Description = "UPS batarya bloğu ve bypass hattı bakım planı teknik yönetici onayıyla takip edilecek.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000002"),
                            IsCompleted = false,
                            ItemType = "PendingMaintenance",
                            MaintenancePlanId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Priority = "Critical",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000001"),
                            Title = "BKM-2026-003 - UPS yıllık bakım takibi"
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 12, 8, 4, 0, 0, DateTimeKind.Utc),
                            Description = "Yük transfer testi veya bypass işlemi öncesinde operasyon merkezi bilgilendirilecek.",
                            IsCompleted = false,
                            ItemType = "CriticalNote",
                            Priority = "High",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000001"),
                            Title = "Level Merkez yük transferi sırasında haber verilecek"
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Terminal A AHU besleme sıcaklığı ve sensör okumaları akşam vardiyasında kontrol edilecek.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000003"),
                            FaultId = new Guid("60000000-0000-0000-0000-000000000011"),
                            IsCompleted = false,
                            ItemType = "OpenFault",
                            Priority = "High",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000002"),
                            Title = "ARZ-2026-011 - AHU sıcaklık takibi"
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 8, 12, 16, 3, 0, 0, DateTimeKind.Utc),
                            Description = "Haftalık test sonrası jeneratör çalışma sesi ve yağ basıncı değerleri vardiya boyunca izlenecek.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            IsCompleted = false,
                            ItemType = "EquipmentToWatch",
                            Priority = "Medium",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000002"),
                            Title = "EQ-00032 - Jeneratör çalışma sesi izlenecek"
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 8, 12, 16, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Saha turunda jeneratör yakıt seviyesi ve sızıntı kontrolü yapılacak.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            IsCompleted = false,
                            ItemType = "OngoingWork",
                            Priority = "Medium",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000002"),
                            Title = "Jeneratör yakıt seviyesi manuel kontrolü"
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 8, 12, 23, 45, 0, 0, DateTimeKind.Utc),
                            Description = "PLC panel haberleşme alarmları gece vardiyasında kontrol edildi.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000004"),
                            IsCompleted = true,
                            ItemType = "EquipmentToWatch",
                            Priority = "Low",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000003"),
                            Title = "EQ-00067 - PLC panel haberleşme durumu",
                            UpdatedAt = new DateTime(2026, 8, 12, 23, 58, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 8, 12, 23, 47, 0, 0, DateTimeKind.Utc),
                            Description = "Saat başı SCADA aktif alarm listesi kontrol edilip kritik alarmlar not alınacak.",
                            IsCompleted = false,
                            ItemType = "OngoingWork",
                            Priority = "Medium",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000003"),
                            Title = "SCADA alarm listesi nöbet kontrolü"
                        },
                        new
                        {
                            Id = new Guid("74100000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 8, 12, 23, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Gece vardiyasında Level Merkez girişinde plan dışı çalışma olup olmadığı kontrol edilecek.",
                            IsCompleted = false,
                            ItemType = "CriticalNote",
                            Priority = "Critical",
                            ShiftHandoverId = new Guid("74000000-0000-0000-0000-000000000003"),
                            Title = "Level Merkez girişinde çalışma izni kontrolü"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.TechnicalSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TechnicalSystems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "SYS-GEN",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Jeneratör"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "SYS-UPS",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "UPS"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "SYS-HVAC",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "HVAC"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Code = "SYS-ELC",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Elektrik"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Code = "SYS-AUT",
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Otomasyon Paneli"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ResponsibleUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PlannedDate");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("Status");

                    b.ToTable("TestPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Jeneratör otomatik çalışma ve transfer senaryosu doğrulaması.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Frequency = "Haftalık",
                            PlannedDate = new DateOnly(2026, 8, 3),
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Status = "Completed",
                            TestType = "Haftalık Jeneratör Testi",
                            UpdatedAt = new DateTime(2026, 8, 3, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("72000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UPS bypass ve yük transfer testi.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Frequency = "Aylık",
                            PlannedDate = new DateOnly(2026, 8, 4),
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Status = "Completed",
                            TestType = "UPS Yük Transfer Testi",
                            UpdatedAt = new DateTime(2026, 8, 4, 10, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("72000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "AHU çalışma, sıcaklık ve drenaj testleri.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Frequency = "Aylık",
                            PlannedDate = new DateOnly(2026, 8, 6),
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Status = "Completed",
                            TestType = "HVAC Çalışma Testi",
                            UpdatedAt = new DateTime(2026, 8, 6, 14, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("72000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PLC panel giriş/çıkış sinyal doğrulaması.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000004"),
                            Frequency = "3 Aylık",
                            PlannedDate = new DateOnly(2026, 8, 7),
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Status = "Completed",
                            TestType = "PLC I/O Testi",
                            UpdatedAt = new DateTime(2026, 8, 7, 11, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("72000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acil durum yük devreye alma senaryosu.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Frequency = "Tek Seferlik",
                            PlannedDate = new DateOnly(2026, 8, 9),
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Status = "Completed",
                            TestType = "Acil Durum Senaryo Testi",
                            UpdatedAt = new DateTime(2026, 8, 9, 9, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("72000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UPS batarya otonomi süresi ve alarm eşikleri test edilecek.",
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Frequency = "6 Aylık",
                            PlannedDate = new DateOnly(2026, 8, 18),
                            ResponsibleUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Status = "Planned",
                            TestType = "UPS Batarya Otonomi Testi"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbnormalCondition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TestPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Result");

                    b.HasIndex("TestDate");

                    b.HasIndex("TestPlanId");

                    b.HasIndex("TestedByUserId");

                    b.ToTable("TestRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 3, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Jeneratör otomatik olarak devreye girdi, gerilim ve frekans değerleri normal aralıkta izlendi.",
                            DurationMinutes = 35,
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Result = "Success",
                            TestDate = new DateTime(2026, 8, 3, 8, 30, 0, 0, DateTimeKind.Utc),
                            TestPlanId = new Guid("72000000-0000-0000-0000-000000000001"),
                            TestType = "Haftalık Jeneratör Testi",
                            TestedByUserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("73000000-0000-0000-0000-000000000002"),
                            AbnormalCondition = "Transfer sonrası kısa süreli bypass alarmı izlendi.",
                            CreatedAt = new DateTime(2026, 8, 4, 10, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Yük transferi tamamlandı ancak alarm eşiği bakımda yeniden değerlendirilecek.",
                            DurationMinutes = 25,
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Result = "ConditionalSuccess",
                            TestDate = new DateTime(2026, 8, 4, 10, 10, 0, 0, DateTimeKind.Utc),
                            TestPlanId = new Guid("72000000-0000-0000-0000-000000000002"),
                            TestType = "UPS Yük Transfer Testi",
                            TestedByUserId = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("73000000-0000-0000-0000-000000000003"),
                            AbnormalCondition = "Besleme havası sıcaklığı hedef aralığa düşmedi.",
                            CreatedAt = new DateTime(2026, 8, 6, 14, 5, 0, 0, DateTimeKind.Utc),
                            Description = "AHU soğutma performansı yetersiz. Bakım planı ile filtre ve sensör kontrolleri takip edilecek.",
                            DurationMinutes = 40,
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Result = "Failed",
                            TestDate = new DateTime(2026, 8, 6, 14, 5, 0, 0, DateTimeKind.Utc),
                            TestPlanId = new Guid("72000000-0000-0000-0000-000000000003"),
                            TestType = "HVAC Çalışma Testi",
                            TestedByUserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("73000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 7, 11, 40, 0, 0, DateTimeKind.Utc),
                            Description = "Tüm dijital giriş/çıkış noktaları SCADA üzerinden doğrulandı.",
                            DurationMinutes = 55,
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000004"),
                            Result = "Success",
                            TestDate = new DateTime(2026, 8, 7, 11, 40, 0, 0, DateTimeKind.Utc),
                            TestPlanId = new Guid("72000000-0000-0000-0000-000000000004"),
                            TestType = "PLC I/O Testi",
                            TestedByUserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("73000000-0000-0000-0000-000000000005"),
                            AbnormalCondition = "Yük alma süresi kabul kriterine çok yakın ölçüldü.",
                            CreatedAt = new DateTime(2026, 8, 9, 9, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Değer sınırda olduğu için tekrar test planlanacak.",
                            DurationMinutes = 30,
                            EquipmentId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Result = "RetestRequired",
                            TestDate = new DateTime(2026, 8, 9, 9, 45, 0, 0, DateTimeKind.Utc),
                            TestPlanId = new Guid("72000000-0000-0000-0000-000000000005"),
                            TestType = "Acil Durum Senaryo Testi",
                            TestedByUserId = new Guid("40000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BT",
                            Email = "admin@demo.local",
                            FullName = "Admin Kullanıcı",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy1hZG1pbi0wMQ==$4bPH94C+/0I4E/NcauyxiZTaIRbc+p919s+gnQiXw4I=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Title = "Sistem Yöneticisi",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Teknik Otomasyon",
                            Email = "yonetici@demo.local",
                            FullName = "Teknik Yönetici",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy1tYW5hZ2VyMQ==$2JU5bt9x2uS/3kp8oY1vE/qobOLfoTy1SkB90ybtopU=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Title = "Teknik Yönetici",
                            Username = "yonetici"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Teknik Otomasyon",
                            Email = "teknik1@demo.local",
                            FullName = "Teknik Personel 1",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy10ZWNoLTAwMQ==$sf498N38LrE5MyaWcpBXOto0kRMQNFh+bvhz0I6fpSQ=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Title = "Teknik Personel",
                            Username = "teknik1"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operasyon",
                            Email = "operator1@demo.local",
                            FullName = "Operatör 1",
                            IsActive = true,
                            PasswordHash = "pbkdf2-sha256$100000$dGVjaG9wcy1vcGVyLTAwMQ==$f3lnNMIH5Qx0gyXdU4xxnWGdeU3DhcO+MKX/Xooisp0=",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Title = "Operatör",
                            Username = "operator1"
                        });
                });

            modelBuilder.Entity("TechOps.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Equipment", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Location", "Location")
                        .WithMany("Equipment")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.TechnicalSystem", "TechnicalSystem")
                        .WithMany("Equipment")
                        .HasForeignKey("TechnicalSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("TechnicalSystem");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Fault", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "AssignedToUser")
                        .WithMany("AssignedFaults")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.User", "ClosedByUser")
                        .WithMany("ClosedFaults")
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.User", "CreatedByUser")
                        .WithMany("CreatedFaults")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("Faults")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.Location", "Location")
                        .WithMany("Faults")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "ResolvedByUser")
                        .WithMany("ResolvedFaults")
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.TechnicalSystem", "TechnicalSystem")
                        .WithMany("Faults")
                        .HasForeignKey("TechnicalSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("ClosedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Equipment");

                    b.Navigation("Location");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("TechnicalSystem");
                });

            modelBuilder.Entity("TechOps.Api.Entities.FaultAction", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Fault", "Fault")
                        .WithMany("Actions")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "User")
                        .WithMany("FaultActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fault");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Location", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Location", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenancePlan", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "CreatedByUser")
                        .WithMany("CreatedMaintenancePlans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("MaintenancePlans")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "ResponsibleUser")
                        .WithMany("ResponsibleMaintenancePlans")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Equipment");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany("Records")
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechOps.Api.Entities.User", "PerformedByUser")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("MaintenancePlan");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Notification", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftHandover", b =>
                {
                    b.HasOne("TechOps.Api.Entities.User", "HandoverFromUser")
                        .WithMany("ShiftHandoversFrom")
                        .HasForeignKey("HandoverFromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "HandoverToUser")
                        .WithMany("ShiftHandoversTo")
                        .HasForeignKey("HandoverToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandoverFromUser");

                    b.Navigation("HandoverToUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftItem", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("ShiftItems")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.Fault", "Fault")
                        .WithMany("ShiftItems")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany("ShiftItems")
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechOps.Api.Entities.ShiftHandover", "ShiftHandover")
                        .WithMany("Items")
                        .HasForeignKey("ShiftHandoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Fault");

                    b.Navigation("MaintenancePlan");

                    b.Navigation("ShiftHandover");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestPlan", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("TestPlans")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.User", "ResponsibleUser")
                        .WithMany("ResponsibleTestPlans")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestRecord", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Equipment", "Equipment")
                        .WithMany("TestRecords")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechOps.Api.Entities.TestPlan", "TestPlan")
                        .WithMany("Records")
                        .HasForeignKey("TestPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechOps.Api.Entities.User", "TestedByUser")
                        .WithMany("TestRecords")
                        .HasForeignKey("TestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("TestPlan");

                    b.Navigation("TestedByUser");
                });

            modelBuilder.Entity("TechOps.Api.Entities.User", b =>
                {
                    b.HasOne("TechOps.Api.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Equipment", b =>
                {
                    b.Navigation("Faults");

                    b.Navigation("MaintenancePlans");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("ShiftItems");

                    b.Navigation("TestPlans");

                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Fault", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("ShiftItems");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Location", b =>
                {
                    b.Navigation("ChildLocations");

                    b.Navigation("Equipment");

                    b.Navigation("Faults");
                });

            modelBuilder.Entity("TechOps.Api.Entities.MaintenancePlan", b =>
                {
                    b.Navigation("Records");

                    b.Navigation("ShiftItems");
                });

            modelBuilder.Entity("TechOps.Api.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TechOps.Api.Entities.ShiftHandover", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TechnicalSystem", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Faults");
                });

            modelBuilder.Entity("TechOps.Api.Entities.TestPlan", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("TechOps.Api.Entities.User", b =>
                {
                    b.Navigation("AssignedFaults");

                    b.Navigation("AuditLogs");

                    b.Navigation("ClosedFaults");

                    b.Navigation("CreatedFaults");

                    b.Navigation("CreatedMaintenancePlans");

                    b.Navigation("FaultActions");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Notifications");

                    b.Navigation("ResolvedFaults");

                    b.Navigation("ResponsibleMaintenancePlans");

                    b.Navigation("ResponsibleTestPlans");

                    b.Navigation("ShiftHandoversFrom");

                    b.Navigation("ShiftHandoversTo");

                    b.Navigation("TestRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
