// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TechOps.Api.Data;

#nullable disable

namespace TechOps.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822083000_AddShiftAssignments")]
    partial class AddShiftAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new SnapshotProxy().Build(modelBuilder);
        }

        private sealed class SnapshotProxy : AppDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                BuildModel(modelBuilder);
            }
        }
    }
}
